# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.32.x # use the fixed version to not introduce new linters unexpectedly

run:
  tests: false
  skip-files:
    - ".*_mock\\.go$"
  skip-dirs:
    - doc

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0

  misspell:
    locale: US
  gocritic: # go-critic docs: https://go-critic.github.io/overview.html
    enabled-tags:
      - performance
      - style
      - experimental
  lll:
    # Increased line length to support go-generate build lines
    line-length: 180

linters: # List of available linters: https://github.com/golangci/golangci-lint#enabled-by-default-linters
  enable-all: true
  disable:
    - exhaustivestruct
    - wrapcheck