pull_request_rules:
  - name: Automatic merge on dependabot requests
    conditions:
      - "author=dependabot[bot]"
      - "base=master"
        - check-success=lint
        - check-success=test
        - check-success=coverage
        - check-success=codecov/project
        - check-success=codecov/patch
    actions:
      merge:
        method: merge
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=lint
      - check-success=test
      - check-success=coverage
      - check-success=codecov/project
      - check-success=codecov/patch
    actions:
      merge:
        method: merge
