version: "3.7"
services:
  tviso:
    image: rodolpheche/wiremock:2.26.3-alpine
    container_name: tviso
    hostname: tviso
    ports:
      - 8080:8080
    volumes:
      - "./tests/stubs:/home/wiremock"
      - "./var/wiremock:/var/wiremock/extensions"
    command: --jetty-acceptor-threads 8 --verbose
    #command: --jetty-acceptor-threads 8 --extensions com.opentable.extension.BodyTransformer --verbose