version: "3.7"
services:
  tviso:
    image: rodolpheche/wiremock:2.26.3-alpine
    container_name: tviso
    hostname: tviso
    ports:
      - 8080:8080
    volumes:
      - "./tests/stubs:/home/wiremock"
      - "./var/wiremock:/var/wiremock/extensions"
    command: --jetty-acceptor-threads 8 --verbose
    #command: --jetty-acceptor-threads 8 --extensions com.opentable.extension.BodyTransformer --verbose
  mongo:
    image: mongo:4.2-bionic
    restart: always
    ports:
      - 27017:27017
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: tvisodb
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    #environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: tvisodb